"""edit column name from create_by to owner_id

Revision ID: 40a575e71d0e
Revises: 27a986889490
Create Date: 2026-08-21 09:25:26.029642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a575e71d0e'
down_revision: Union[str, None] = '27a986889490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_constraint('projects_created_by_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_created_by_fkey', 'projects', 'users', ['created_by'], ['id'])
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###
