"""add description to workspace

Revision ID: 6c68db5766d3
Revises: b100ca36c54e
Create Date: 2026-08-20 11:39:27.072148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c68db5766d3'
down_revision: Union[str, None] = 'b100ca36c54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('description', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'description')
    # ### end Alembic commands ###
