"""logs_activity table

Revision ID: 9cc6e9a89fd3
Revises: 95fa654b9e80
Create Date: 2026-08-21 19:54:14.102936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc6e9a89fd3'
down_revision: Union[str, None] = '95fa654b9e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
